version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: movies-database
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d 
      - mysql_data:/var/lib/mysql             
    ports:
      - "3306:3306"

volumes:
  mysql_data:
